PayglWeb/Controllers/AppController.cs
using Microsoft.AspNetCore.Mvc;
using PayglService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PayglWeb.Controllers
{
    public class AppController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "Index";
            return View();
        }

        [HttpGet("operation")]
        public IActionResult Operation()
        {
            ViewBag.Title = "Operation";
            return View();
        }

        [HttpGet("group")]
        public IActionResult Group()
        {
            ViewBag.Title = "Group";
            return View();
        }

        [HttpGet("import")]
        public IActionResult Import()
        {
            ViewBag.Title = "Import";
            return View();
        }

        [HttpGet("search")]
        public IActionResult Search()
        {
            ViewBag.Title = "Search";
            return View();
        }

        [HttpGet("filters")]
        public IActionResult Filters()
        {
            ViewBag.Title = "Filters";
            return View();
        }

        [HttpGet("dashboards")]
        public IActionResult Dashboards()
        {
            ViewBag.Title = "Dashboards";
            return View();
        }

        [HttpGet("analysis")]
        public IActionResult Analysis()
        {
            ViewBag.Title = "Analysis";
            return View();
        }

        [HttpGet("importsettings")]
        public IActionResult ImportSettings()
        {
            ViewBag.Title = "ImportSettings";
            return View();
        }
    }
}

PayglWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="~/ClientApp/dist/favicon.png" type="image/png">
    <title>Paygl</title>
    <meta name="viewport" content="width=device-width" charset="utf-8" />
    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    <environment names="Staging, Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
</head>
<body style="padding-top: 80px;">
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="./"><img src="~/ClientApp/dist/favicon-full.png" width="99" height="30"></a>
            <button class="navbar-toggler" aria-expanded="false" aria-controls="navbarColor03" aria-label="Toggle navigation" type="button" data-target="#navbarColor03" data-toggle="collapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download" aria-expanded="false">Transakcje <span class="caret"></span></a>
                        <div class="dropdown-menu" aria-labelledby="download">
                            <a class="nav-link" asp-controller="App" asp-action="Operation">Nowa operacja</a>
                            <a class="nav-link" asp-controller="App" asp-action="Group">Nowa grupa</a>
                            <a class="nav-link" asp-controller="App" asp-action="Import">Importuj dane</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download" aria-expanded="false">Analiza<span class="caret"></span></a>
                        <div class="dropdown-menu" aria-labelledby="download">
                            <a class="nav-link" asp-controller="App" asp-action="Search">Wyszukiwanie</a>
                            <a class="nav-link" asp-controller="App" asp-action="Filters">Filtry</a>
                            <a class="nav-link" asp-controller="App" asp-action="Dashboards">Tablice</a>
                            <a class="nav-link" asp-controller="App" asp-action="Analysis">Analiza</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download" aria-expanded="false">Ustawienia<span class="caret"></span></a>
                        <div class="dropdown-menu" aria-labelledby="download">
                            <a class="nav-link" asp-controller="App" asp-action="ImportSettings">Import</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/index.js"></script>
    </environment>
    <environment names="Staging, Production">
        <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-3.4.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"></script>
        <script src="//ajax.aspnetcdn.com/ajax/bootstrap/4.3.1/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"></script>
        <script src="~/dist/payglweb.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("scripts", false)
</body>
</html>